### PR TITLE
(Almost) completed Elm 0.16 to Elm 0.18 upgrade

### PR DESCRIPTION
**Pull request by CarlinLiao**
I've run it locally and it works. I haven't thoroughly tested it, but I haven't thoroughly tested the original Elm 0.16 version either.

Notable changes include:
- refactoring all Elm files to be compliant with Elm 0.18, with significant rewriting in `UI.elm` and `MoreEvents.elm`, and some style changes
- updated `UI.js` to comply with Elm 0.17/0.18
- upgraded `elm-webpack-loader` version to ensure compatibility with Elm 0.18
- changes to `package.json` and `elm-package.json` to update versions and meta information

### CODE REVIEW

**Comment by kks32** [comment]
I'm able to visualise the map, but the options like being able to filter types of roads, or distance from London Eye, traffic at different times don't display / modify the map. Not sure if this is a local issue. @gac55 Could you confirm?

**Comment by CarlinLiao** [comment]
It seems like the functionality of all the menus are broken. I should've known it wouldn't be that easy.

**Comment by CarlinLiao** [comment]
It seems like the functionality of all the menus are broken. I should've known it wouldn't be that easy.

**Comment by gac55** [comment]
Just test it and yes, unfortunately it seems to have broken the models functionality. Can you elaborate on your `send` hypothesis? 

Keep it up! @CarlinLiao !

cc @kks32

**Comment by CarlinLiao** [comment]
Essentially I commented out the `send` (and `sendSpecial`) functionalities because they were almost/just as/more difficult to refactor to 0.18 as `MoreEvents.elm`, and the program was able to compile without them. As it turns out the `send` function is a key part of processing what to do when the client changes their view of which nodes to see, which timeframe to view, etc., so it needs to be reimplemented in order to enable those features.

**Comment by CarlinLiao** [comment]
This has been sitting open for years lol. May we merge or close? @kks32 @gac55

**Comment by gac55** [comment]
Oh wow!!! Blast from the past. Let's merge - shall you do the honours since you did the hard work?

**Comment by CarlinLiao** [comment]
I don't have write access so I can't. Take it away, Gerry!

**Comment by gac55** [comment]
image

Thanks @CarlinLiao !

**Pull request merged**
